[build]
  command = "cd client && npm install && npm run build"
  publish = "client/dist/public"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 